### ISSUE TITLE
Vue js build failed

### ISSUE THREAD

**Issue by realrecordzLab** [hampoelz/Capacitor-NodeJS#1]
I've noticed that if I create the required files inside the `dist` folder of my vue app, the build will fail because it's unable to found the capacitor nodejs module and the dist folder is deleted. Maybe it's better to deploy them inside the public folder of vuejs project?

**Comment by hampoelz** [comment]
Hey @realrecordzLab!

Do I understand correctly, your app (I guess it's an android app) builds correctly without the Capacitor-NodeJS plugin, but as soon as you add this plugin to your Vue and Capacitor project the build fails?

If you set the `webDir` and `nodeDir` variables correctly in the capacitor configuration file, this plugin should work.

If that's not the case, it would be great if you could create a minimal sample project.
