### ISSUE TITLE
Separate example projects in a new repo

### ISSUE THREAD

**Issue by jrobeson** [hampoelz/Capacitor-NodeJS#10]
Branches shouldn't be used the way they are being used for the example project.
It'd be best to just put the example projects in an examples directory in the main branch or alternatively as separate repositories. 

I'd vote for separate repositories.

**Comment by hampoelz** [comment]
You're right, that's not the best solution at the moment. Personally, I'm against putting the sample projects mixed with the plugin code in the main branch. I'll create a separate repository.

**Comment by hampoelz** [comment]
The example projects are now located in the [hampoelz/Capacitor-NodeJS_Examples](https://github.com/hampoelz/Capacitor-NodeJS_Examples) repository.

The different examples are in branches so that major changes can be easily merged across all projects.
