### ISSUE TITLE
How does one use the new builtin bridge package from the node project?

### ISSUE THREAD

**Issue by jrobeson** [hampoelz/Capacitor-NodeJS#18]
I develop my node application separately from my capacitor project and it works completely standalone. I copied the bridge js into my program (with proper attribution and licensing) and then use it as an event listener (Since the channels extend event listener when binding isn't available).  I can then test reaction to various events without involving capacitor at all.  

I'm not quite sure how i can still do that with the new architecture.

Is there some way to still import the bridge for that usage and not load it twice or will the built bridge.js still work for that case?

**Comment by hampoelz** [comment]
When you add your forked bridge to the dependencies, it will overwrite the built-in bridge module. 

However, you could also load your custom bridge module as a "built-in" module in your Node.js environment. When you run the project with Capacitor, it would use the bridge module from this plugin. When you run the  standalone, it would use your bridge module.

To archive this, create a directory for your local built-in modules and start Node.js with the `NODE_PATH` environment variable pointing to that directory. For example, `NODE_PATH="/path/to/your/builtin_modules/" node app.js`.

You can read more in the corresponding Node.js dokumentation:
https://nodejs.org/api/modules.html#loading-from-the-global-folders

**Comment by jrobeson** [comment]
i'm not sure what you mean by "to my dependencies" I just have it in a my application source atm, since i thought a separate npm package was going to be published, and it works fine.

This new bridge however says `throw new Error('No IPC channel has been established between the Node.js process and the Capacitor layer.');` ALthough there is no such error in `NativeMobileBridge` only `NativeDesktopBridge`.

**Comment by jrobeson** [comment]
Oh, when i actually try to use this project with my copy of your new bridge I get

`TypeError: Cannot read properties of undefined (reading 'addListener')`
for `eventChannel.addListener('msg-from-capacitor', (args: CapacitorMsg) => {`

**Comment by jrobeson** [comment]
Ah ignore hte last comment. when i copied the entire bridge and `ChannelPayloadData` from definitions it started to work again.

**Comment by hampoelz** [comment]
> i'm not sure what you mean by "to my dependencies" I just have it in a my application source atm, since i thought a separate npm package was going to be published, and it works fine.

Oh, I assumed you packaged your custom bridge module as a local npm package. 

> This new bridge however says `throw new Error('No IPC channel has been established between the Node.js process and the Capacitor layer.');` Although there is no such throw in `NativeMobileBridge` only `NativeDesktopBridge`.

When the bridge module is used on a desktop platform (if `process.platform` is not `android` or `ios`), the `NativeDesktopBridge` is used, which tries to establish a channel with electron. By using the module in a standalone project _(on the desktop)_, the electron backend is missing and therefore no channel can be established.

Wouldn't it be easiest to create some kind of wrapper around the included bridge module? Depending on whether the built-in bridge is available, the bridge module should be used, otherwise your own bridge should be used. Maybe something like this:

```typescript
// your_custom_bridge.js:
const EventEmitter = require('events');

let nativeBridge;
try {
    nativeBridge = require('bridge');
} catch (ex) { }

const nativeChannel = nativeBridge?.channel;
const customChannel = new EventEmitter();

// do something with customChannel

exports.customBridge = nativeChannel ?? customChannel;
```

Note that I haven't tested this code.

Alternatively, you could package your bridge module as a local npm module and set the `NODE_PATH` variable as mentioned above.

**Comment by jrobeson** [comment]
yeah i will have a make a bridge module apparently, I was just surprised that it worked fine before, but doesn't now. Thanks for the response. I'll just close this bug.
