### ISSUE TITLE
Add a method to stop nodejs

### ISSUE THREAD

**Issue by jrobeson** [hampoelz/Capacitor-NodeJS#19]
If i change the configuration or arguments passed to nodejs then it'd be nice to be able to restart just nodejs instead of the whole app.

**Comment by hampoelz** [comment]
Unfortunately, this is not supported by `nodejs-mobile` at the moment.

**Comment by JohnRSim** [comment]
https://github.com/nodejs-mobile/nodejs-mobile/issues/135 - hopefully soon..
