### ISSUE TITLE
How to use manual mode start?

### ISSUE THREAD

**Issue by ghost** [hampoelz/Capacitor-NodeJS#20]
I set `startMode: 'manual'` in my `capacitor.config.ts`

I have my built application in `public/nodejs` so it gets copied into the build.

I call it like this: `await NodeJS.start({ script: 'dist/index.js', env: { NODE_ENV: 'production' } });`

The file s located at `/data/data/com.example.myApp/files/nodejs/public/dist/index.js` (via android device explorer)

I added `Logger.info(CapacitorNodeJSPlugin.LOGGER_TAG, "NATIVE START" + Arrays.toString(arguments));` right before the call to ` nativeStart(arguments, environmentVariables, true);` in `NodeProcess.java` and I see: ` NATIVE START[node, /data/user/0/com.example.myApp/files/nodejs/public/dist/index.js]` so it does seem like it should use that file. However it doesnt seem to actually start my App.  Before  I go any farther in debugging, is this all I need to do?

EDIT:  I should say that when i turn off manual mode and switch back to `whenReady()` the app boots as expected

**Comment by jrobeson** [comment]
aha! I'll give it a go. thanks. It'd be nice to see it in one of the examples at some point.

**Comment by jrobeson** [comment]
I tried that approach and it didn't work. Is it possible you could try it in one of the examples?

**Comment by hampoelz** [comment]
The example was unfortunately out of date. I've updated everything and added some new examples. Take a look at the [`example/manual_start`](https://github.com/hampoelz/Capacitor-NodeJS_Examples/tree/example/manual_start) branch.
