### ISSUE TITLE
How do I use this plugin in Quasar's capacitor. 

### ISSUE THREAD

**Issue by 2061360308** [hampoelz/Capacitor-NodeJS#22]
my project like this：
![图片](https://github.com/hampoelz/Capacitor-NodeJS/assets/42377282/e8305578-1244-4f8a-a08b-3481befe56f1)

quasar hava a “\src-capacitor\capacitor.config.json“ and I configure it in this file
```json
{
  "appId": "cn.test",
  "appName": "Quasar App",
  "webDir": "www",
  "server": {
    "androidScheme": "https",
    "url": "http://192.168.1.9:9500"
  },
  "plugins": {
    "CapacitorNodeJS": {
      "nodeDir": "nodejs"
    }
  }
}

```

I have created the nodejs folder in the ' src capacitor' and root directory，like：
![图片](https://github.com/hampoelz/Capacitor-NodeJS/assets/42377282/b96dc6a8-96a1-4c50-9655-b385714970f6)
Finally, I imported and used an example of the plugin in “indexPage. vue”
![图片](https://github.com/hampoelz/Capacitor-NodeJS/assets/42377282/fb357896-5015-432f-981b-b355db3b02a3)

The results I obtained show that the plugin did not import properly
![图片](https://github.com/hampoelz/Capacitor-NodeJS/assets/42377282/3d4deadf-3cf4-4ab4-b92f-17a5cc746c0e)

quasar docs：https://quasar.dev/docs

**Comment by hampoelz** [comment]
I've never used quasar before, but as long as the plugin is not recognized at all, I don't think I can do much about it. 

Could you try adding another Capacitor plugin to your project and check if this plugin is recognized? If other Capacitor plugins are also not properly recognized, the problem may be with quasar.

**Comment by 2061360308** [comment]
> I've never used quasar before, but as long as the plugin is not recognized at all, I don't think I can do much about it.
> 
> Could you try adding another Capacitor plugin to your project and check if this plugin is recognized? If other Capacitor plugins are also not properly recognized, the problem may be with quasar.

Thank you for your answer. This plugin is available when I create a new project using capacitor, and I will seek help from the quasar community.

**Comment by 2061360308** [comment]
I successfully solved this problem. 

1. First, create nodejs in the “/src-capacitor/www”. 
2. Secondly I run the  "npm install https://github.com/hampoelz/capacitor-nodejs/releases/download/v1.0.0-beta.6/capacitor-nodejs.tgz"  command in the "src-capacitor" directory. 
3. Then use "npx cap sync"。


This way, it can be used normally。

But there is a problem that when you use the quasar command to build, the www directory will be overwritten, and every time you update the nodejs directory, you need to manually run "npx cap sync".At present, I haven't found a better way
