### ISSUE TITLE
Execution failed for task ':capacitor-nodejs:compileDebugJavaWithJavac'. > error: invalid source release: 17

### ISSUE THREAD

**Issue by surajpra** [hampoelz/Capacitor-NodeJS#24]
Execution failed for task ':capacitor-nodejs:compileDebugJavaWithJavac'.
> error: invalid source release: 17

![image](https://github.com/hampoelz/Capacitor-NodeJS/assets/41315923/48d032a0-6476-4c4d-8bd9-a3ed2e649290)
![image](https://github.com/hampoelz/Capacitor-NodeJS/assets/41315923/5c9bb9b3-cb1e-473c-9349-6e573999d851)
![image](https://github.com/hampoelz/Capacitor-NodeJS/assets/41315923/99785cae-2441-4105-8220-0dbd787afa2b)

**Comment by hampoelz** [comment]
It is difficult to solve the problem without further information.

- It looks like you are using quasar. Does the same error occur with a plain Capacitor project?
- Does the build work if you only use the other Capacitor plugins, without the NodeJS plugin?
- Are you using the latest Android Studio version and is your Gradle JVM configured to Java version 17?

**Comment by surajpra** [comment]
It is difficult to solve the problem without further information.

Yes, i am using quasar, but its working fine with plain capacitor project but not with quasar capacitor project. 
i am using latest android studio version already updated gradle 8.0.0 and java version 17.

but iam not able to execute 

error - Unable to copy the Node.js project from APK.

**Comment by surajpra** [comment]
my main purpose is, i want to use escpos plugin 
https://www.npmjs.com/package/escpos
with capacitorjs.

**Comment by hampoelz** [comment]
The error message "Unable to copy the Node.js project from APK." indicates that your nodejs project folder is not included when bundling.

In your project structure, the nodejs project folder is located directly in the `capacitor-src` folder, but usually it should be located in the the `static` subfolder _(or in the case of quasar probably in `capacitor-src/static`?)_ to ensure that your nodejs project is taken into account by the bundler.

See https://github.com/hampoelz/Capacitor-NodeJS#minimal-example
