### ISSUE TITLE
Could not run on device only in debug mode

### ISSUE THREAD

**Issue by sce9sc** [hampoelz/Capacitor-NodeJS#4]
Hi, 

I created a simple capacitor android app and everything seems fine on the emulator , but when I tried it on a real device unfortunately it didn't .  Strangely though when opening the android studio and instead of running it I pressed debug It worked. 

Do you have any idea ??

Thanks

**Comment by sce9sc** [comment]
Found it . The problem is that the web view is starting to quickly and the node.js has not started yet . 
I added an alert in the web view before everything and waited for a while , when i closed the alert Everything worked.

**Comment by hampoelz** [comment]
Hey @sce9sc,
thank you for the report.

This is indeed an issue that the nodejs engine takes longer to load than the web view on some devices. I'll add an event that fires after the nodejs engine is fully started.

**Comment by hampoelz** [comment]
You're right, that would be a simple workaround. But i think it's better to integrate something like this directly into the plugin and add it to the docs and qickstart guide to generally avoid such issues in future.

**Comment by hampoelz** [comment]
Fixed in v0.0.2 which adds `whenReady()` method.
