### ISSUE TITLE
Allow manual startup of the node.js runtime and pass environment variables

### ISSUE THREAD

**Issue by jrobeson** [hampoelz/Capacitor-NodeJS#8]
As per https://github.com/nodejs-mobile/nodejs-mobile-cordova#nodejsstartscriptfilename-callback--options

It'd also be nice to have be able to pass environment variables as well.

I'm embedding a web service for an "offline only" version of my application, so I need to be able to configure it on boot based on settings provided by the android side of things. Environment varaibles are more convenient for me personally, but just being able to pass the args from the android side would be ok too.

 I'm curently just using `Os.setenv` in a copy of the plugin since I haven't yet expanded my java skills.

**Comment by hampoelz** [comment]
Regarding the environment variables, are there any particular advantages? If so, I would consider adding some as presets which can be toggled in the start options. Allowing to set every env variable would be out of scope of this plugin.

**Comment by jrobeson** [comment]
My app is built like https://12factor.net/ (except secrets can come from things like docker or vault nowadays). so the database url (sqlite in this case) mounted path and other things come from env variables.

**Comment by jrobeson** [comment]
I wasn't exactly clear what I wanted the signature to look like. Something like https://nodejs.org/api/child_process.html#child_processspawncommand-args-options , but obviously it's not a being treated as a child process here so we can omit most of the args.

so it'd look like

```ts
// this is basically node's definition of process.env minus the generic
interface EnvVars {
 [key: string]: string | undefined;
}

interface StartOptions {
  env: EnvVars;
  // any other options could be added here, like cwd 
}
start(fileName: string, args: string[], opts: StartOptions)
```

**Comment by hampoelz** [comment]
I like your idea. However, this wouldn't work with the current ElectronJS integration. Therefore the implementation will take some time.

**Comment by hampoelz** [comment]
Added in v1.0.0-beta.4

You can now use the `startMode` configuration and the `start()` method to manually start the Node.js runtime. In addition, arguments can be passed to the main script and environment variables for the Node.js runtime can be set.
